AUTH_SCHEMA = 'auth'
BROKERS_SCHEMA = 'brokers'
STRATEGIES_SCHEMA = 'strategies'
TRADING_SCHEMA = 'trading'
PORTFOLIO_SCHEMA = 'portfolio'
RISK_SCHEMA = 'risk'
BACKTEST_SCHEMA = 'backtest'
ANALYTICS_SCHEMA = 'analytics'
AUDIT_SCHEMA = 'audit'

ALL_SCHEMAS = [
    AUTH_SCHEMA,
    BROKERS_SCHEMA,
    STRATEGIES_SCHEMA,
    TRADING_SCHEMA,
    PORTFOLIO_SCHEMA,
    RISK_SCHEMA,
    BACKTEST_SCHEMA,
    ANALYTICS_SCHEMA,
    AUDIT_SCHEMA,
]
